[versions]
androidPluginGradle = "7.2.2"
androidx-activity = "1.4.0"
androidx-compose = "1.2.1"
androidx-compose-compiler = "1.3.0"
androidx-compose-wear = "1.0.2"
androidx-lifecycle = "2.4.1"
androidx-wear = "1.2.0"
dagger = "2.38.1"
logcat = "0.1"
kotlin = "1.7.10"
retrofit = "2.9.0"
moshi = "1.14.0"
ksp = "1.7.10-1.0.6"

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[libraries]
androidPluginGradle = { module = "com.android.tools.build:gradle", version.ref = "androidPluginGradle" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidx.activity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx.activity" }
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "androidx.compose.compiler" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx.compose" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx.compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidx.compose" }
androidx-compose-wear-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "androidx.compose.wear" }
androidx-compose-wear-material = { module = "androidx.wear.compose:compose-material", version.ref = "androidx.compose.wear" }
androidx-compose-wear-navigation = { module = "androidx.wear.compose:compose-navigation", version.ref = "androidx.compose.wear" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx.compose" }
androidx-compose-ui-toolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx.compose" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx.lifecycle" }
androidx-wear = { module = "androidx.wear:wear", version.ref = "androidx.wear" }
dagger-hilt-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "dagger" }
dagger-hilt-runtime = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
logcat = { module = "com.squareup.logcat:logcat", version.ref = "logcat" }
kotlin-pluginGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
